import streamlit as st
import master_script
import os
import io
from contextlib import redirect_stdout
from glob import glob

st.set_page_config(page_title="Arctic Energy Storage LCOS Model", layout="wide")

st.title("Arctic Energy Storage LCOS Model")

# -------------------------------
# USER INPUTS
# -------------------------------
st.header("Input Parameters")

col1, col2 = st.columns(2)

with col1:
    Power = st.number_input("Power (MW)", value=100.0)
    DD = st.number_input("Discharge Duration (hours)", value=1.0)
    charges_per_year = st.number_input("Charges per Year", value=372.76)
    Powercost = st.number_input("Electricity Cost (USD/kWh)", value=0.05)

with col2:
    interest_rate = st.number_input("Discount Rate", value=0.08)
    project_lifespan = st.number_input("Project Lifespan (years)", value=50)

st.subheader("Temperature Inputs (°C)")

tcol1, tcol2 = st.columns(2)

with tcol1:
    arctic_winter_low = st.number_input("Arctic Winter Low (°C)", value=-40)
    arctic_mean_annual = st.number_input("Arctic Mean Annual (°C)", value=-10)

with tcol2:
    baseline_winter_low = st.number_input("Baseline Winter Low (°C)", value=0)
    baseline_mean_annual = st.number_input("Baseline Mean Annual (°C)", value=20)

# Bundle temperatures into correct list format
selected_Tamb = [
    arctic_winter_low,
    baseline_winter_low,
    arctic_mean_annual,
    baseline_mean_annual
]

# -------------------------------
# RUN BUTTON
# -------------------------------
if st.button("Run LCOS Model"):

    inputs = {
        "Power": Power,
        "DD": DD,
        "charges_per_year": charges_per_year,
        "selected_Tamb": selected_Tamb,
        "Powercost": Powercost,
        "interest_rate": interest_rate,
        "project_lifespan": project_lifespan,
    }

    st.info("Running calculations...please wait.")

    # -----------------------------------------------------
    # SUPPRESS CONSOLE OUTPUT FROM ALL SUBPROGRAMS
    # -----------------------------------------------------
    f = io.StringIO()
    with redirect_stdout(f):
        results = master_script.run(inputs)

    console_log = f.getvalue()  # suppressed but accessible

    st.success("Model run complete!")

    # -----------------------------------------------------
    # DISPLAY NUMERIC RESULTS
    # -----------------------------------------------------
    st.header("Computed Results")

    cols = st.columns(3)
    cols[0].metric("Baseline CAPEX ($)", f"{results['baselineCAPEX']:,.0f}")
    cols[1].metric("New CAPEX ($)", f"{results['newCAPEX']:,.0f}")
    cols[2].metric("LCOS Change (%)", f"{results['LCOSchange']:.2f}")

    cols2 = st.columns(3)
    cols2[0].metric("Baseline OPEX ($/yr)", f"{results['baselineOPEX']:,.0f}")
    cols2[1].metric("New OPEX ($/yr)", f"{results['newOPEX']:,.0f}")
    cols2[2].metric("Baseline Storage (MWh/yr)", f"{results['baselinestorage']:,.0f}")

    # -----------------------------------------------------
    # DISPLAY PLOTS GENERATED BY master_script
    # -----------------------------------------------------
    st.header("Generated Plots")

    plot_files = sorted(glob("*.png") + glob("*.jpg") + glob("*.jpeg"))

    if len(plot_files) == 0:
        st.warning("No plots were found. Ensure master_script saves figures to PNG files.")
    else:
        for pf in plot_files:
            st.image(pf, caption=os.path.basename(pf), use_column_width=True)

    # -----------------------------------------------------
    # OPTIONAL DEBUG LOG
    # -----------------------------------------------------
    with st.expander("Show console output (debug)"):
        st.text(console_log)
